trigger:
  branches:
    include:
      - main  # Trigger pipeline on changes to the main branch

pool:
  name: 'work-agent'  # Use the self-hosted agent pool (work-agent)

variables:
  imageName: 'python-app'  # Name of your Docker image
  acrName: 'workacr1'      # Your ACR name
  registry: '$(acrName).azurecr.io'  # Correct reference to registry
  tag: '$(Build.BuildId)'  # Tag the image with the build ID

steps:
# Step 1: Install Azure CLI
- task: Bash@3
  displayName: 'Install Azure CLI'
  inputs:
    targetType: 'inline'
    script: |
      echo "Installing Azure CLI..."
      sudo apt-get update
      sudo apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

# Step 2: Verify Azure CLI version
- task: Bash@3
  displayName: 'Verify Azure CLI Version'
  inputs:
    targetType: 'inline'
    script: |
      echo "Checking Azure CLI version..."
      az --version

# Step 3: Log in to Azure using the ARM service connection
- task: AzureCLI@2
  inputs:
    azureSubscription: 'work1-arm'  # Use the ARM service connection name
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Logging into Azure..."
      az login --identity

# Step 4: Log in to ACR using the Docker service connection
- task: Docker@2
  inputs:
    command: 'login'
    containerRegistry: 'work1'  # Use the Docker service connection name

# Step 5: Build and Push Docker Image to ACR
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'work1'  # Use the Docker service connection name
    repository: '$(imageName)'  # Correct reference to image name (python-app)
    tags: '$(tag)'  # Tag the image with the build ID
    dockerfile: '**/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'

# Step 6: Deploy to AKS using the ARM service connection
- task: AzureCLI@2
  inputs:
    azureSubscription: 'work1-arm'  # Use the ARM service connection name
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Deploying to AKS..."
      kubectl apply -f deployment.yaml
